set dotenv-load

@default:
	just --list

ysweet:
	Y_SWEET_STORE=${YS_STORE} \
	PORT=${YS_PORT} \
	Y_SWEET_CHECKPOINT_FREQ_SECONDS=60 \
	Y_SWEET_AUTH=${YS_PRIVATE_KEY} \
	Y_SWEET_URL_PREFIX=${YS_URL_PREFIX} \
		bunx y-sweet@latest serve

@dev:
	bun run --watch src/index.ts
